import { Box, Container, Typography } from '@mui/material';
import { IPostProps, PostCard } from '../../components';

const posts : IPostProps[] = [
  {
    title: 'Post Title',
    subtitle: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid saepe expedita, repellat nobis.',
    coverImage: 'https://source.unsplash.com/random',
    tags: ['tag1', 'tag2', 'tag3'],
    creationDate: new Date(),
    content: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique, quas! Tempora, vitae cum ipsum voluptatibus quidem sequi animi excepturi iusto, alias amet corporis! Minus non doloribus obcaecati repellendus dignissimos ipsum. Laudantium, inventore accusantium quo at modi reiciendis aliquid error explicabo soluta autem, eum ut provident obcaecati distinctio nemo quaerat eos nisi tenetur repellendus velit, neque qui id. Repudiandae, necessitatibus consectetur! Nostrum placeat omnis dolor beatae odit cupiditate quo ut nam labore, quaerat dolores perspiciatis sapiente eius sint, a nemo rerum delectus quod laudantium aperiam soluta? Distinctio dolorem eaque laboriosam illo. Eos recusandae, dolores beatae commodi accusantium soluta? Quos consequuntur repellat quidem soluta aut, omnis rem ut earum quisquam magni fugiat laboriosam ratione ab sequi ex cupiditate, molestias dignissimos aliquid? Placeat. Vel reprehenderit quae voluptate fugiat neque, repellendus dolorem. Quibusdam, laudantium quos tempore nobis dolores expedita sint eum. Provident, culpa? Vel dolor praesentium repudiandae totam laboriosam maxime magnam, consequuntur neque quod? Odit dicta tempore fuga optio, itaque velit! Voluptate voluptates officiis architecto sit aspernatur, ratione cum distinctio placeat perspiciatis natus, dolorem, quis error voluptatibus quod corrupti quam tempore. Culpa, aliquam? Fuga. Reiciendis magnam ad molestias animi eum sapiente accusamus vel quasi placeat corporis impedit delectus velit, labore dolorem doloribus dolorum, nesciunt ab repudiandae! Exercitationem necessitatibus suscipit in vitae, perspiciatis itaque porro! Natus vel minus quia voluptate eius magnam excepturi, dolore explicabo cupiditate sunt, similique dolorum exercitationem inventore, saepe eos id quae. Voluptas consectetur autem vero officiis accusamus. Repellendus omnis odio optio.', 
  },
  {
    title: 'Post Title',
    subtitle: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid saepe expedita, repellat nobis.',
    coverImage: 'https://source.unsplash.com/random',
    tags: ['tag1', 'tag2', 'tag3'],
    creationDate: new Date(),
    content: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique, quas! Tempora, vitae cum ipsum voluptatibus quidem sequi animi excepturi iusto, alias amet corporis! Minus non doloribus obcaecati repellendus dignissimos ipsum. Laudantium, inventore accusantium quo at modi reiciendis aliquid error explicabo soluta autem, eum ut provident obcaecati distinctio nemo quaerat eos nisi tenetur repellendus velit, neque qui id. Repudiandae, necessitatibus consectetur! Nostrum placeat omnis dolor beatae odit cupiditate quo ut nam labore, quaerat dolores perspiciatis sapiente eius sint, a nemo rerum delectus quod laudantium aperiam soluta? Distinctio dolorem eaque laboriosam illo. Eos recusandae, dolores beatae commodi accusantium soluta? Quos consequuntur repellat quidem soluta aut, omnis rem ut earum quisquam magni fugiat laboriosam ratione ab sequi ex cupiditate, molestias dignissimos aliquid? Placeat. Vel reprehenderit quae voluptate fugiat neque, repellendus dolorem. Quibusdam, laudantium quos tempore nobis dolores expedita sint eum. Provident, culpa? Vel dolor praesentium repudiandae totam laboriosam maxime magnam, consequuntur neque quod? Odit dicta tempore fuga optio, itaque velit! Voluptate voluptates officiis architecto sit aspernatur, ratione cum distinctio placeat perspiciatis natus, dolorem, quis error voluptatibus quod corrupti quam tempore. Culpa, aliquam? Fuga. Reiciendis magnam ad molestias animi eum sapiente accusamus vel quasi placeat corporis impedit delectus velit, labore dolorem doloribus dolorum, nesciunt ab repudiandae! Exercitationem necessitatibus suscipit in vitae, perspiciatis itaque porro! Natus vel minus quia voluptate eius magnam excepturi, dolore explicabo cupiditate sunt, similique dolorum exercitationem inventore, saepe eos id quae. Voluptas consectetur autem vero officiis accusamus. Repellendus omnis odio optio.', 
  },
  {
    title: 'Post Title',
    subtitle: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid saepe expedita, repellat nobis.',
    coverImage: 'https://source.unsplash.com/random',
    tags: ['tag1', 'tag2', 'tag3'],
    creationDate: new Date(),
    content: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique, quas! Tempora, vitae cum ipsum voluptatibus quidem sequi animi excepturi iusto, alias amet corporis! Minus non doloribus obcaecati repellendus dignissimos ipsum. Laudantium, inventore accusantium quo at modi reiciendis aliquid error explicabo soluta autem, eum ut provident obcaecati distinctio nemo quaerat eos nisi tenetur repellendus velit, neque qui id. Repudiandae, necessitatibus consectetur! Nostrum placeat omnis dolor beatae odit cupiditate quo ut nam labore, quaerat dolores perspiciatis sapiente eius sint, a nemo rerum delectus quod laudantium aperiam soluta? Distinctio dolorem eaque laboriosam illo. Eos recusandae, dolores beatae commodi accusantium soluta? Quos consequuntur repellat quidem soluta aut, omnis rem ut earum quisquam magni fugiat laboriosam ratione ab sequi ex cupiditate, molestias dignissimos aliquid? Placeat. Vel reprehenderit quae voluptate fugiat neque, repellendus dolorem. Quibusdam, laudantium quos tempore nobis dolores expedita sint eum. Provident, culpa? Vel dolor praesentium repudiandae totam laboriosam maxime magnam, consequuntur neque quod? Odit dicta tempore fuga optio, itaque velit! Voluptate voluptates officiis architecto sit aspernatur, ratione cum distinctio placeat perspiciatis natus, dolorem, quis error voluptatibus quod corrupti quam tempore. Culpa, aliquam? Fuga. Reiciendis magnam ad molestias animi eum sapiente accusamus vel quasi placeat corporis impedit delectus velit, labore dolorem doloribus dolorum, nesciunt ab repudiandae! Exercitationem necessitatibus suscipit in vitae, perspiciatis itaque porro! Natus vel minus quia voluptate eius magnam excepturi, dolore explicabo cupiditate sunt, similique dolorum exercitationem inventore, saepe eos id quae. Voluptas consectetur autem vero officiis accusamus. Repellendus omnis odio optio.', 
  },
  {
    title: 'Post Title',
    subtitle: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid saepe expedita, repellat nobis.',
    coverImage: 'https://source.unsplash.com/random',
    tags: ['tag1', 'tag2', 'tag3'],
    creationDate: new Date(),
    content: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique, quas! Tempora, vitae cum ipsum voluptatibus quidem sequi animi excepturi iusto, alias amet corporis! Minus non doloribus obcaecati repellendus dignissimos ipsum. Laudantium, inventore accusantium quo at modi reiciendis aliquid error explicabo soluta autem, eum ut provident obcaecati distinctio nemo quaerat eos nisi tenetur repellendus velit, neque qui id. Repudiandae, necessitatibus consectetur! Nostrum placeat omnis dolor beatae odit cupiditate quo ut nam labore, quaerat dolores perspiciatis sapiente eius sint, a nemo rerum delectus quod laudantium aperiam soluta? Distinctio dolorem eaque laboriosam illo. Eos recusandae, dolores beatae commodi accusantium soluta? Quos consequuntur repellat quidem soluta aut, omnis rem ut earum quisquam magni fugiat laboriosam ratione ab sequi ex cupiditate, molestias dignissimos aliquid? Placeat. Vel reprehenderit quae voluptate fugiat neque, repellendus dolorem. Quibusdam, laudantium quos tempore nobis dolores expedita sint eum. Provident, culpa? Vel dolor praesentium repudiandae totam laboriosam maxime magnam, consequuntur neque quod? Odit dicta tempore fuga optio, itaque velit! Voluptate voluptates officiis architecto sit aspernatur, ratione cum distinctio placeat perspiciatis natus, dolorem, quis error voluptatibus quod corrupti quam tempore. Culpa, aliquam? Fuga. Reiciendis magnam ad molestias animi eum sapiente accusamus vel quasi placeat corporis impedit delectus velit, labore dolorem doloribus dolorum, nesciunt ab repudiandae! Exercitationem necessitatibus suscipit in vitae, perspiciatis itaque porro! Natus vel minus quia voluptate eius magnam excepturi, dolore explicabo cupiditate sunt, similique dolorum exercitationem inventore, saepe eos id quae. Voluptas consectetur autem vero officiis accusamus. Repellendus omnis odio optio.', 
  },
  {
    title: 'Post Title',
    subtitle: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid saepe expedita, repellat nobis.',
    coverImage: 'https://source.unsplash.com/random',
    tags: ['tag1', 'tag2', 'tag3'],
    creationDate: new Date(),
    content: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique, quas! Tempora, vitae cum ipsum voluptatibus quidem sequi animi excepturi iusto, alias amet corporis! Minus non doloribus obcaecati repellendus dignissimos ipsum. Laudantium, inventore accusantium quo at modi reiciendis aliquid error explicabo soluta autem, eum ut provident obcaecati distinctio nemo quaerat eos nisi tenetur repellendus velit, neque qui id. Repudiandae, necessitatibus consectetur! Nostrum placeat omnis dolor beatae odit cupiditate quo ut nam labore, quaerat dolores perspiciatis sapiente eius sint, a nemo rerum delectus quod laudantium aperiam soluta? Distinctio dolorem eaque laboriosam illo. Eos recusandae, dolores beatae commodi accusantium soluta? Quos consequuntur repellat quidem soluta aut, omnis rem ut earum quisquam magni fugiat laboriosam ratione ab sequi ex cupiditate, molestias dignissimos aliquid? Placeat. Vel reprehenderit quae voluptate fugiat neque, repellendus dolorem. Quibusdam, laudantium quos tempore nobis dolores expedita sint eum. Provident, culpa? Vel dolor praesentium repudiandae totam laboriosam maxime magnam, consequuntur neque quod? Odit dicta tempore fuga optio, itaque velit! Voluptate voluptates officiis architecto sit aspernatur, ratione cum distinctio placeat perspiciatis natus, dolorem, quis error voluptatibus quod corrupti quam tempore. Culpa, aliquam? Fuga. Reiciendis magnam ad molestias animi eum sapiente accusamus vel quasi placeat corporis impedit delectus velit, labore dolorem doloribus dolorum, nesciunt ab repudiandae! Exercitationem necessitatibus suscipit in vitae, perspiciatis itaque porro! Natus vel minus quia voluptate eius magnam excepturi, dolore explicabo cupiditate sunt, similique dolorum exercitationem inventore, saepe eos id quae. Voluptas consectetur autem vero officiis accusamus. Repellendus omnis odio optio.', 
  },
  {
    title: 'Post Title',
    subtitle: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid saepe expedita, repellat nobis.',
    coverImage: 'https://source.unsplash.com/random',
    tags: ['tag1', 'tag2', 'tag3'],
    creationDate: new Date(),
    content: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique, quas! Tempora, vitae cum ipsum voluptatibus quidem sequi animi excepturi iusto, alias amet corporis! Minus non doloribus obcaecati repellendus dignissimos ipsum. Laudantium, inventore accusantium quo at modi reiciendis aliquid error explicabo soluta autem, eum ut provident obcaecati distinctio nemo quaerat eos nisi tenetur repellendus velit, neque qui id. Repudiandae, necessitatibus consectetur! Nostrum placeat omnis dolor beatae odit cupiditate quo ut nam labore, quaerat dolores perspiciatis sapiente eius sint, a nemo rerum delectus quod laudantium aperiam soluta? Distinctio dolorem eaque laboriosam illo. Eos recusandae, dolores beatae commodi accusantium soluta? Quos consequuntur repellat quidem soluta aut, omnis rem ut earum quisquam magni fugiat laboriosam ratione ab sequi ex cupiditate, molestias dignissimos aliquid? Placeat. Vel reprehenderit quae voluptate fugiat neque, repellendus dolorem. Quibusdam, laudantium quos tempore nobis dolores expedita sint eum. Provident, culpa? Vel dolor praesentium repudiandae totam laboriosam maxime magnam, consequuntur neque quod? Odit dicta tempore fuga optio, itaque velit! Voluptate voluptates officiis architecto sit aspernatur, ratione cum distinctio placeat perspiciatis natus, dolorem, quis error voluptatibus quod corrupti quam tempore. Culpa, aliquam? Fuga. Reiciendis magnam ad molestias animi eum sapiente accusamus vel quasi placeat corporis impedit delectus velit, labore dolorem doloribus dolorum, nesciunt ab repudiandae! Exercitationem necessitatibus suscipit in vitae, perspiciatis itaque porro! Natus vel minus quia voluptate eius magnam excepturi, dolore explicabo cupiditate sunt, similique dolorum exercitationem inventore, saepe eos id quae. Voluptas consectetur autem vero officiis accusamus. Repellendus omnis odio optio.', 
  },
  {
    title: 'Post Title',
    subtitle: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid saepe expedita, repellat nobis.',
    coverImage: 'https://source.unsplash.com/random',
    tags: ['tag1', 'tag2', 'tag3'],
    creationDate: new Date(),
    content: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique, quas! Tempora, vitae cum ipsum voluptatibus quidem sequi animi excepturi iusto, alias amet corporis! Minus non doloribus obcaecati repellendus dignissimos ipsum. Laudantium, inventore accusantium quo at modi reiciendis aliquid error explicabo soluta autem, eum ut provident obcaecati distinctio nemo quaerat eos nisi tenetur repellendus velit, neque qui id. Repudiandae, necessitatibus consectetur! Nostrum placeat omnis dolor beatae odit cupiditate quo ut nam labore, quaerat dolores perspiciatis sapiente eius sint, a nemo rerum delectus quod laudantium aperiam soluta? Distinctio dolorem eaque laboriosam illo. Eos recusandae, dolores beatae commodi accusantium soluta? Quos consequuntur repellat quidem soluta aut, omnis rem ut earum quisquam magni fugiat laboriosam ratione ab sequi ex cupiditate, molestias dignissimos aliquid? Placeat. Vel reprehenderit quae voluptate fugiat neque, repellendus dolorem. Quibusdam, laudantium quos tempore nobis dolores expedita sint eum. Provident, culpa? Vel dolor praesentium repudiandae totam laboriosam maxime magnam, consequuntur neque quod? Odit dicta tempore fuga optio, itaque velit! Voluptate voluptates officiis architecto sit aspernatur, ratione cum distinctio placeat perspiciatis natus, dolorem, quis error voluptatibus quod corrupti quam tempore. Culpa, aliquam? Fuga. Reiciendis magnam ad molestias animi eum sapiente accusamus vel quasi placeat corporis impedit delectus velit, labore dolorem doloribus dolorum, nesciunt ab repudiandae! Exercitationem necessitatibus suscipit in vitae, perspiciatis itaque porro! Natus vel minus quia voluptate eius magnam excepturi, dolore explicabo cupiditate sunt, similique dolorum exercitationem inventore, saepe eos id quae. Voluptas consectetur autem vero officiis accusamus. Repellendus omnis odio optio.', 
  },
  {
    title: 'Post Title',
    subtitle: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid saepe expedita, repellat nobis.',
    coverImage: 'https://source.unsplash.com/random',
    tags: ['tag1', 'tag2', 'tag3'],
    creationDate: new Date(),
    content: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique, quas! Tempora, vitae cum ipsum voluptatibus quidem sequi animi excepturi iusto, alias amet corporis! Minus non doloribus obcaecati repellendus dignissimos ipsum. Laudantium, inventore accusantium quo at modi reiciendis aliquid error explicabo soluta autem, eum ut provident obcaecati distinctio nemo quaerat eos nisi tenetur repellendus velit, neque qui id. Repudiandae, necessitatibus consectetur! Nostrum placeat omnis dolor beatae odit cupiditate quo ut nam labore, quaerat dolores perspiciatis sapiente eius sint, a nemo rerum delectus quod laudantium aperiam soluta? Distinctio dolorem eaque laboriosam illo. Eos recusandae, dolores beatae commodi accusantium soluta? Quos consequuntur repellat quidem soluta aut, omnis rem ut earum quisquam magni fugiat laboriosam ratione ab sequi ex cupiditate, molestias dignissimos aliquid? Placeat. Vel reprehenderit quae voluptate fugiat neque, repellendus dolorem. Quibusdam, laudantium quos tempore nobis dolores expedita sint eum. Provident, culpa? Vel dolor praesentium repudiandae totam laboriosam maxime magnam, consequuntur neque quod? Odit dicta tempore fuga optio, itaque velit! Voluptate voluptates officiis architecto sit aspernatur, ratione cum distinctio placeat perspiciatis natus, dolorem, quis error voluptatibus quod corrupti quam tempore. Culpa, aliquam? Fuga. Reiciendis magnam ad molestias animi eum sapiente accusamus vel quasi placeat corporis impedit delectus velit, labore dolorem doloribus dolorum, nesciunt ab repudiandae! Exercitationem necessitatibus suscipit in vitae, perspiciatis itaque porro! Natus vel minus quia voluptate eius magnam excepturi, dolore explicabo cupiditate sunt, similique dolorum exercitationem inventore, saepe eos id quae. Voluptas consectetur autem vero officiis accusamus. Repellendus omnis odio optio.', 
  },
  {
    title: 'Post Title',
    subtitle: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid saepe expedita, repellat nobis.',
    coverImage: 'https://source.unsplash.com/random',
    tags: ['tag1', 'tag2', 'tag3'],
    creationDate: new Date(),
    content: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique, quas! Tempora, vitae cum ipsum voluptatibus quidem sequi animi excepturi iusto, alias amet corporis! Minus non doloribus obcaecati repellendus dignissimos ipsum. Laudantium, inventore accusantium quo at modi reiciendis aliquid error explicabo soluta autem, eum ut provident obcaecati distinctio nemo quaerat eos nisi tenetur repellendus velit, neque qui id. Repudiandae, necessitatibus consectetur! Nostrum placeat omnis dolor beatae odit cupiditate quo ut nam labore, quaerat dolores perspiciatis sapiente eius sint, a nemo rerum delectus quod laudantium aperiam soluta? Distinctio dolorem eaque laboriosam illo. Eos recusandae, dolores beatae commodi accusantium soluta? Quos consequuntur repellat quidem soluta aut, omnis rem ut earum quisquam magni fugiat laboriosam ratione ab sequi ex cupiditate, molestias dignissimos aliquid? Placeat. Vel reprehenderit quae voluptate fugiat neque, repellendus dolorem. Quibusdam, laudantium quos tempore nobis dolores expedita sint eum. Provident, culpa? Vel dolor praesentium repudiandae totam laboriosam maxime magnam, consequuntur neque quod? Odit dicta tempore fuga optio, itaque velit! Voluptate voluptates officiis architecto sit aspernatur, ratione cum distinctio placeat perspiciatis natus, dolorem, quis error voluptatibus quod corrupti quam tempore. Culpa, aliquam? Fuga. Reiciendis magnam ad molestias animi eum sapiente accusamus vel quasi placeat corporis impedit delectus velit, labore dolorem doloribus dolorum, nesciunt ab repudiandae! Exercitationem necessitatibus suscipit in vitae, perspiciatis itaque porro! Natus vel minus quia voluptate eius magnam excepturi, dolore explicabo cupiditate sunt, similique dolorum exercitationem inventore, saepe eos id quae. Voluptas consectetur autem vero officiis accusamus. Repellendus omnis odio optio.', 
  },
  {
    title: 'Post Title',
    subtitle: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid saepe expedita, repellat nobis.',
    coverImage: 'https://source.unsplash.com/random',
    tags: ['tag1', 'tag2', 'tag3'],
    creationDate: new Date(),
    content: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique, quas! Tempora, vitae cum ipsum voluptatibus quidem sequi animi excepturi iusto, alias amet corporis! Minus non doloribus obcaecati repellendus dignissimos ipsum. Laudantium, inventore accusantium quo at modi reiciendis aliquid error explicabo soluta autem, eum ut provident obcaecati distinctio nemo quaerat eos nisi tenetur repellendus velit, neque qui id. Repudiandae, necessitatibus consectetur! Nostrum placeat omnis dolor beatae odit cupiditate quo ut nam labore, quaerat dolores perspiciatis sapiente eius sint, a nemo rerum delectus quod laudantium aperiam soluta? Distinctio dolorem eaque laboriosam illo. Eos recusandae, dolores beatae commodi accusantium soluta? Quos consequuntur repellat quidem soluta aut, omnis rem ut earum quisquam magni fugiat laboriosam ratione ab sequi ex cupiditate, molestias dignissimos aliquid? Placeat. Vel reprehenderit quae voluptate fugiat neque, repellendus dolorem. Quibusdam, laudantium quos tempore nobis dolores expedita sint eum. Provident, culpa? Vel dolor praesentium repudiandae totam laboriosam maxime magnam, consequuntur neque quod? Odit dicta tempore fuga optio, itaque velit! Voluptate voluptates officiis architecto sit aspernatur, ratione cum distinctio placeat perspiciatis natus, dolorem, quis error voluptatibus quod corrupti quam tempore. Culpa, aliquam? Fuga. Reiciendis magnam ad molestias animi eum sapiente accusamus vel quasi placeat corporis impedit delectus velit, labore dolorem doloribus dolorum, nesciunt ab repudiandae! Exercitationem necessitatibus suscipit in vitae, perspiciatis itaque porro! Natus vel minus quia voluptate eius magnam excepturi, dolore explicabo cupiditate sunt, similique dolorum exercitationem inventore, saepe eos id quae. Voluptas consectetur autem vero officiis accusamus. Repellendus omnis odio optio.', 
  },
  {
    title: 'Post Title',
    subtitle: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid saepe expedita, repellat nobis.',
    coverImage: 'https://source.unsplash.com/random',
    tags: ['tag1', 'tag2', 'tag3'],
    creationDate: new Date(),
    content: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique, quas! Tempora, vitae cum ipsum voluptatibus quidem sequi animi excepturi iusto, alias amet corporis! Minus non doloribus obcaecati repellendus dignissimos ipsum. Laudantium, inventore accusantium quo at modi reiciendis aliquid error explicabo soluta autem, eum ut provident obcaecati distinctio nemo quaerat eos nisi tenetur repellendus velit, neque qui id. Repudiandae, necessitatibus consectetur! Nostrum placeat omnis dolor beatae odit cupiditate quo ut nam labore, quaerat dolores perspiciatis sapiente eius sint, a nemo rerum delectus quod laudantium aperiam soluta? Distinctio dolorem eaque laboriosam illo. Eos recusandae, dolores beatae commodi accusantium soluta? Quos consequuntur repellat quidem soluta aut, omnis rem ut earum quisquam magni fugiat laboriosam ratione ab sequi ex cupiditate, molestias dignissimos aliquid? Placeat. Vel reprehenderit quae voluptate fugiat neque, repellendus dolorem. Quibusdam, laudantium quos tempore nobis dolores expedita sint eum. Provident, culpa? Vel dolor praesentium repudiandae totam laboriosam maxime magnam, consequuntur neque quod? Odit dicta tempore fuga optio, itaque velit! Voluptate voluptates officiis architecto sit aspernatur, ratione cum distinctio placeat perspiciatis natus, dolorem, quis error voluptatibus quod corrupti quam tempore. Culpa, aliquam? Fuga. Reiciendis magnam ad molestias animi eum sapiente accusamus vel quasi placeat corporis impedit delectus velit, labore dolorem doloribus dolorum, nesciunt ab repudiandae! Exercitationem necessitatibus suscipit in vitae, perspiciatis itaque porro! Natus vel minus quia voluptate eius magnam excepturi, dolore explicabo cupiditate sunt, similique dolorum exercitationem inventore, saepe eos id quae. Voluptas consectetur autem vero officiis accusamus. Repellendus omnis odio optio.', 
  },
  {
    title: 'Post Title',
    subtitle: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid saepe expedita, repellat nobis.',
    coverImage: 'https://source.unsplash.com/random',
    tags: ['tag1', 'tag2', 'tag3'],
    creationDate: new Date(),
    content: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique, quas! Tempora, vitae cum ipsum voluptatibus quidem sequi animi excepturi iusto, alias amet corporis! Minus non doloribus obcaecati repellendus dignissimos ipsum. Laudantium, inventore accusantium quo at modi reiciendis aliquid error explicabo soluta autem, eum ut provident obcaecati distinctio nemo quaerat eos nisi tenetur repellendus velit, neque qui id. Repudiandae, necessitatibus consectetur! Nostrum placeat omnis dolor beatae odit cupiditate quo ut nam labore, quaerat dolores perspiciatis sapiente eius sint, a nemo rerum delectus quod laudantium aperiam soluta? Distinctio dolorem eaque laboriosam illo. Eos recusandae, dolores beatae commodi accusantium soluta? Quos consequuntur repellat quidem soluta aut, omnis rem ut earum quisquam magni fugiat laboriosam ratione ab sequi ex cupiditate, molestias dignissimos aliquid? Placeat. Vel reprehenderit quae voluptate fugiat neque, repellendus dolorem. Quibusdam, laudantium quos tempore nobis dolores expedita sint eum. Provident, culpa? Vel dolor praesentium repudiandae totam laboriosam maxime magnam, consequuntur neque quod? Odit dicta tempore fuga optio, itaque velit! Voluptate voluptates officiis architecto sit aspernatur, ratione cum distinctio placeat perspiciatis natus, dolorem, quis error voluptatibus quod corrupti quam tempore. Culpa, aliquam? Fuga. Reiciendis magnam ad molestias animi eum sapiente accusamus vel quasi placeat corporis impedit delectus velit, labore dolorem doloribus dolorum, nesciunt ab repudiandae! Exercitationem necessitatibus suscipit in vitae, perspiciatis itaque porro! Natus vel minus quia voluptate eius magnam excepturi, dolore explicabo cupiditate sunt, similique dolorum exercitationem inventore, saepe eos id quae. Voluptas consectetur autem vero officiis accusamus. Repellendus omnis odio optio.', 
  },
  {
    title: 'Post Title',
    subtitle: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid saepe expedita, repellat nobis.',
    coverImage: 'https://source.unsplash.com/random',
    tags: ['tag1', 'tag2', 'tag3'],
    creationDate: new Date(),
    content: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique, quas! Tempora, vitae cum ipsum voluptatibus quidem sequi animi excepturi iusto, alias amet corporis! Minus non doloribus obcaecati repellendus dignissimos ipsum. Laudantium, inventore accusantium quo at modi reiciendis aliquid error explicabo soluta autem, eum ut provident obcaecati distinctio nemo quaerat eos nisi tenetur repellendus velit, neque qui id. Repudiandae, necessitatibus consectetur! Nostrum placeat omnis dolor beatae odit cupiditate quo ut nam labore, quaerat dolores perspiciatis sapiente eius sint, a nemo rerum delectus quod laudantium aperiam soluta? Distinctio dolorem eaque laboriosam illo. Eos recusandae, dolores beatae commodi accusantium soluta? Quos consequuntur repellat quidem soluta aut, omnis rem ut earum quisquam magni fugiat laboriosam ratione ab sequi ex cupiditate, molestias dignissimos aliquid? Placeat. Vel reprehenderit quae voluptate fugiat neque, repellendus dolorem. Quibusdam, laudantium quos tempore nobis dolores expedita sint eum. Provident, culpa? Vel dolor praesentium repudiandae totam laboriosam maxime magnam, consequuntur neque quod? Odit dicta tempore fuga optio, itaque velit! Voluptate voluptates officiis architecto sit aspernatur, ratione cum distinctio placeat perspiciatis natus, dolorem, quis error voluptatibus quod corrupti quam tempore. Culpa, aliquam? Fuga. Reiciendis magnam ad molestias animi eum sapiente accusamus vel quasi placeat corporis impedit delectus velit, labore dolorem doloribus dolorum, nesciunt ab repudiandae! Exercitationem necessitatibus suscipit in vitae, perspiciatis itaque porro! Natus vel minus quia voluptate eius magnam excepturi, dolore explicabo cupiditate sunt, similique dolorum exercitationem inventore, saepe eos id quae. Voluptas consectetur autem vero officiis accusamus. Repellendus omnis odio optio.', 
  },
  {
    title: 'Post Title',
    subtitle: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid saepe expedita, repellat nobis.',
    coverImage: 'https://source.unsplash.com/random',
    tags: ['tag1', 'tag2', 'tag3'],
    creationDate: new Date(),
    content: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique, quas! Tempora, vitae cum ipsum voluptatibus quidem sequi animi excepturi iusto, alias amet corporis! Minus non doloribus obcaecati repellendus dignissimos ipsum. Laudantium, inventore accusantium quo at modi reiciendis aliquid error explicabo soluta autem, eum ut provident obcaecati distinctio nemo quaerat eos nisi tenetur repellendus velit, neque qui id. Repudiandae, necessitatibus consectetur! Nostrum placeat omnis dolor beatae odit cupiditate quo ut nam labore, quaerat dolores perspiciatis sapiente eius sint, a nemo rerum delectus quod laudantium aperiam soluta? Distinctio dolorem eaque laboriosam illo. Eos recusandae, dolores beatae commodi accusantium soluta? Quos consequuntur repellat quidem soluta aut, omnis rem ut earum quisquam magni fugiat laboriosam ratione ab sequi ex cupiditate, molestias dignissimos aliquid? Placeat. Vel reprehenderit quae voluptate fugiat neque, repellendus dolorem. Quibusdam, laudantium quos tempore nobis dolores expedita sint eum. Provident, culpa? Vel dolor praesentium repudiandae totam laboriosam maxime magnam, consequuntur neque quod? Odit dicta tempore fuga optio, itaque velit! Voluptate voluptates officiis architecto sit aspernatur, ratione cum distinctio placeat perspiciatis natus, dolorem, quis error voluptatibus quod corrupti quam tempore. Culpa, aliquam? Fuga. Reiciendis magnam ad molestias animi eum sapiente accusamus vel quasi placeat corporis impedit delectus velit, labore dolorem doloribus dolorum, nesciunt ab repudiandae! Exercitationem necessitatibus suscipit in vitae, perspiciatis itaque porro! Natus vel minus quia voluptate eius magnam excepturi, dolore explicabo cupiditate sunt, similique dolorum exercitationem inventore, saepe eos id quae. Voluptas consectetur autem vero officiis accusamus. Repellendus omnis odio optio.', 
  },
  {
    title: 'Post Title',
    subtitle: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid saepe expedita, repellat nobis.',
    coverImage: 'https://source.unsplash.com/random',
    tags: ['tag1', 'tag2', 'tag3'],
    creationDate: new Date(),
    content: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique, quas! Tempora, vitae cum ipsum voluptatibus quidem sequi animi excepturi iusto, alias amet corporis! Minus non doloribus obcaecati repellendus dignissimos ipsum. Laudantium, inventore accusantium quo at modi reiciendis aliquid error explicabo soluta autem, eum ut provident obcaecati distinctio nemo quaerat eos nisi tenetur repellendus velit, neque qui id. Repudiandae, necessitatibus consectetur! Nostrum placeat omnis dolor beatae odit cupiditate quo ut nam labore, quaerat dolores perspiciatis sapiente eius sint, a nemo rerum delectus quod laudantium aperiam soluta? Distinctio dolorem eaque laboriosam illo. Eos recusandae, dolores beatae commodi accusantium soluta? Quos consequuntur repellat quidem soluta aut, omnis rem ut earum quisquam magni fugiat laboriosam ratione ab sequi ex cupiditate, molestias dignissimos aliquid? Placeat. Vel reprehenderit quae voluptate fugiat neque, repellendus dolorem. Quibusdam, laudantium quos tempore nobis dolores expedita sint eum. Provident, culpa? Vel dolor praesentium repudiandae totam laboriosam maxime magnam, consequuntur neque quod? Odit dicta tempore fuga optio, itaque velit! Voluptate voluptates officiis architecto sit aspernatur, ratione cum distinctio placeat perspiciatis natus, dolorem, quis error voluptatibus quod corrupti quam tempore. Culpa, aliquam? Fuga. Reiciendis magnam ad molestias animi eum sapiente accusamus vel quasi placeat corporis impedit delectus velit, labore dolorem doloribus dolorum, nesciunt ab repudiandae! Exercitationem necessitatibus suscipit in vitae, perspiciatis itaque porro! Natus vel minus quia voluptate eius magnam excepturi, dolore explicabo cupiditate sunt, similique dolorum exercitationem inventore, saepe eos id quae. Voluptas consectetur autem vero officiis accusamus. Repellendus omnis odio optio.', 
  },
  {
    title: 'Post Title',
    subtitle: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid saepe expedita, repellat nobis.',
    coverImage: 'https://source.unsplash.com/random',
    tags: ['tag1', 'tag2', 'tag3'],
    creationDate: new Date(),
    content: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique, quas! Tempora, vitae cum ipsum voluptatibus quidem sequi animi excepturi iusto, alias amet corporis! Minus non doloribus obcaecati repellendus dignissimos ipsum. Laudantium, inventore accusantium quo at modi reiciendis aliquid error explicabo soluta autem, eum ut provident obcaecati distinctio nemo quaerat eos nisi tenetur repellendus velit, neque qui id. Repudiandae, necessitatibus consectetur! Nostrum placeat omnis dolor beatae odit cupiditate quo ut nam labore, quaerat dolores perspiciatis sapiente eius sint, a nemo rerum delectus quod laudantium aperiam soluta? Distinctio dolorem eaque laboriosam illo. Eos recusandae, dolores beatae commodi accusantium soluta? Quos consequuntur repellat quidem soluta aut, omnis rem ut earum quisquam magni fugiat laboriosam ratione ab sequi ex cupiditate, molestias dignissimos aliquid? Placeat. Vel reprehenderit quae voluptate fugiat neque, repellendus dolorem. Quibusdam, laudantium quos tempore nobis dolores expedita sint eum. Provident, culpa? Vel dolor praesentium repudiandae totam laboriosam maxime magnam, consequuntur neque quod? Odit dicta tempore fuga optio, itaque velit! Voluptate voluptates officiis architecto sit aspernatur, ratione cum distinctio placeat perspiciatis natus, dolorem, quis error voluptatibus quod corrupti quam tempore. Culpa, aliquam? Fuga. Reiciendis magnam ad molestias animi eum sapiente accusamus vel quasi placeat corporis impedit delectus velit, labore dolorem doloribus dolorum, nesciunt ab repudiandae! Exercitationem necessitatibus suscipit in vitae, perspiciatis itaque porro! Natus vel minus quia voluptate eius magnam excepturi, dolore explicabo cupiditate sunt, similique dolorum exercitationem inventore, saepe eos id quae. Voluptas consectetur autem vero officiis accusamus. Repellendus omnis odio optio.', 
  },
  {
    title: 'Post Title',
    subtitle: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid saepe expedita, repellat nobis.',
    coverImage: 'https://source.unsplash.com/random',
    tags: ['tag1', 'tag2', 'tag3'],
    creationDate: new Date(),
    content: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique, quas! Tempora, vitae cum ipsum voluptatibus quidem sequi animi excepturi iusto, alias amet corporis! Minus non doloribus obcaecati repellendus dignissimos ipsum. Laudantium, inventore accusantium quo at modi reiciendis aliquid error explicabo soluta autem, eum ut provident obcaecati distinctio nemo quaerat eos nisi tenetur repellendus velit, neque qui id. Repudiandae, necessitatibus consectetur! Nostrum placeat omnis dolor beatae odit cupiditate quo ut nam labore, quaerat dolores perspiciatis sapiente eius sint, a nemo rerum delectus quod laudantium aperiam soluta? Distinctio dolorem eaque laboriosam illo. Eos recusandae, dolores beatae commodi accusantium soluta? Quos consequuntur repellat quidem soluta aut, omnis rem ut earum quisquam magni fugiat laboriosam ratione ab sequi ex cupiditate, molestias dignissimos aliquid? Placeat. Vel reprehenderit quae voluptate fugiat neque, repellendus dolorem. Quibusdam, laudantium quos tempore nobis dolores expedita sint eum. Provident, culpa? Vel dolor praesentium repudiandae totam laboriosam maxime magnam, consequuntur neque quod? Odit dicta tempore fuga optio, itaque velit! Voluptate voluptates officiis architecto sit aspernatur, ratione cum distinctio placeat perspiciatis natus, dolorem, quis error voluptatibus quod corrupti quam tempore. Culpa, aliquam? Fuga. Reiciendis magnam ad molestias animi eum sapiente accusamus vel quasi placeat corporis impedit delectus velit, labore dolorem doloribus dolorum, nesciunt ab repudiandae! Exercitationem necessitatibus suscipit in vitae, perspiciatis itaque porro! Natus vel minus quia voluptate eius magnam excepturi, dolore explicabo cupiditate sunt, similique dolorum exercitationem inventore, saepe eos id quae. Voluptas consectetur autem vero officiis accusamus. Repellendus omnis odio optio.', 
  },
  {
    title: 'Post Title',
    subtitle: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid saepe expedita, repellat nobis.',
    coverImage: 'https://source.unsplash.com/random',
    tags: ['tag1', 'tag2', 'tag3'],
    creationDate: new Date(),
    content: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique, quas! Tempora, vitae cum ipsum voluptatibus quidem sequi animi excepturi iusto, alias amet corporis! Minus non doloribus obcaecati repellendus dignissimos ipsum. Laudantium, inventore accusantium quo at modi reiciendis aliquid error explicabo soluta autem, eum ut provident obcaecati distinctio nemo quaerat eos nisi tenetur repellendus velit, neque qui id. Repudiandae, necessitatibus consectetur! Nostrum placeat omnis dolor beatae odit cupiditate quo ut nam labore, quaerat dolores perspiciatis sapiente eius sint, a nemo rerum delectus quod laudantium aperiam soluta? Distinctio dolorem eaque laboriosam illo. Eos recusandae, dolores beatae commodi accusantium soluta? Quos consequuntur repellat quidem soluta aut, omnis rem ut earum quisquam magni fugiat laboriosam ratione ab sequi ex cupiditate, molestias dignissimos aliquid? Placeat. Vel reprehenderit quae voluptate fugiat neque, repellendus dolorem. Quibusdam, laudantium quos tempore nobis dolores expedita sint eum. Provident, culpa? Vel dolor praesentium repudiandae totam laboriosam maxime magnam, consequuntur neque quod? Odit dicta tempore fuga optio, itaque velit! Voluptate voluptates officiis architecto sit aspernatur, ratione cum distinctio placeat perspiciatis natus, dolorem, quis error voluptatibus quod corrupti quam tempore. Culpa, aliquam? Fuga. Reiciendis magnam ad molestias animi eum sapiente accusamus vel quasi placeat corporis impedit delectus velit, labore dolorem doloribus dolorum, nesciunt ab repudiandae! Exercitationem necessitatibus suscipit in vitae, perspiciatis itaque porro! Natus vel minus quia voluptate eius magnam excepturi, dolore explicabo cupiditate sunt, similique dolorum exercitationem inventore, saepe eos id quae. Voluptas consectetur autem vero officiis accusamus. Repellendus omnis odio optio.', 
  },
  {
    title: 'Post Title',
    subtitle: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid saepe expedita, repellat nobis.',
    coverImage: 'https://source.unsplash.com/random',
    tags: ['tag1', 'tag2', 'tag3'],
    creationDate: new Date(),
    content: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique, quas! Tempora, vitae cum ipsum voluptatibus quidem sequi animi excepturi iusto, alias amet corporis! Minus non doloribus obcaecati repellendus dignissimos ipsum. Laudantium, inventore accusantium quo at modi reiciendis aliquid error explicabo soluta autem, eum ut provident obcaecati distinctio nemo quaerat eos nisi tenetur repellendus velit, neque qui id. Repudiandae, necessitatibus consectetur! Nostrum placeat omnis dolor beatae odit cupiditate quo ut nam labore, quaerat dolores perspiciatis sapiente eius sint, a nemo rerum delectus quod laudantium aperiam soluta? Distinctio dolorem eaque laboriosam illo. Eos recusandae, dolores beatae commodi accusantium soluta? Quos consequuntur repellat quidem soluta aut, omnis rem ut earum quisquam magni fugiat laboriosam ratione ab sequi ex cupiditate, molestias dignissimos aliquid? Placeat. Vel reprehenderit quae voluptate fugiat neque, repellendus dolorem. Quibusdam, laudantium quos tempore nobis dolores expedita sint eum. Provident, culpa? Vel dolor praesentium repudiandae totam laboriosam maxime magnam, consequuntur neque quod? Odit dicta tempore fuga optio, itaque velit! Voluptate voluptates officiis architecto sit aspernatur, ratione cum distinctio placeat perspiciatis natus, dolorem, quis error voluptatibus quod corrupti quam tempore. Culpa, aliquam? Fuga. Reiciendis magnam ad molestias animi eum sapiente accusamus vel quasi placeat corporis impedit delectus velit, labore dolorem doloribus dolorum, nesciunt ab repudiandae! Exercitationem necessitatibus suscipit in vitae, perspiciatis itaque porro! Natus vel minus quia voluptate eius magnam excepturi, dolore explicabo cupiditate sunt, similique dolorum exercitationem inventore, saepe eos id quae. Voluptas consectetur autem vero officiis accusamus. Repellendus omnis odio optio.', 
  },
  {
    title: 'Post Title',
    subtitle: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid saepe expedita, repellat nobis.',
    coverImage: 'https://source.unsplash.com/random',
    tags: ['tag1', 'tag2', 'tag3'],
    creationDate: new Date(),
    content: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique, quas! Tempora, vitae cum ipsum voluptatibus quidem sequi animi excepturi iusto, alias amet corporis! Minus non doloribus obcaecati repellendus dignissimos ipsum. Laudantium, inventore accusantium quo at modi reiciendis aliquid error explicabo soluta autem, eum ut provident obcaecati distinctio nemo quaerat eos nisi tenetur repellendus velit, neque qui id. Repudiandae, necessitatibus consectetur! Nostrum placeat omnis dolor beatae odit cupiditate quo ut nam labore, quaerat dolores perspiciatis sapiente eius sint, a nemo rerum delectus quod laudantium aperiam soluta? Distinctio dolorem eaque laboriosam illo. Eos recusandae, dolores beatae commodi accusantium soluta? Quos consequuntur repellat quidem soluta aut, omnis rem ut earum quisquam magni fugiat laboriosam ratione ab sequi ex cupiditate, molestias dignissimos aliquid? Placeat. Vel reprehenderit quae voluptate fugiat neque, repellendus dolorem. Quibusdam, laudantium quos tempore nobis dolores expedita sint eum. Provident, culpa? Vel dolor praesentium repudiandae totam laboriosam maxime magnam, consequuntur neque quod? Odit dicta tempore fuga optio, itaque velit! Voluptate voluptates officiis architecto sit aspernatur, ratione cum distinctio placeat perspiciatis natus, dolorem, quis error voluptatibus quod corrupti quam tempore. Culpa, aliquam? Fuga. Reiciendis magnam ad molestias animi eum sapiente accusamus vel quasi placeat corporis impedit delectus velit, labore dolorem doloribus dolorum, nesciunt ab repudiandae! Exercitationem necessitatibus suscipit in vitae, perspiciatis itaque porro! Natus vel minus quia voluptate eius magnam excepturi, dolore explicabo cupiditate sunt, similique dolorum exercitationem inventore, saepe eos id quae. Voluptas consectetur autem vero officiis accusamus. Repellendus omnis odio optio.', 
  },
];

export const Blog = () => {
  return (
    <Container>
      <Typography variant="h1">
        Blog
      </Typography>
      <Box gap={1} display='flex' flexDirection='column'>
        {posts.map(post => <PostCard key={post.title} {...post} variant='regular'/>)}
      </Box>
    </Container>
  );
};